version: "2"

services:
  tasker:
    image: strm/tasker
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      configuration: |
        schedule:
          - every: minute
          task: hello
          tasks:
            docker:
            - name: hello
            image: ubuntu:latest
            script:
              - echo Hello world from Tasker